version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes: ['./data:/var/lib/mysql']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypass123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: mypass123 
    networks:
      - wpsite

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - '8082:80'
    restart: always
    volumes: ['./html:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite

networks:
  wpsite:
